-- Input file for Euphemia 11.4_fix3

-- delete TABLES DATA
DELETE FROM Algorithm_Parameters;
DELETE FROM Block_Order_Period_Constraints;
DELETE FROM BLOCK_ORDER_LINKS;
DELETE FROM BLOCK_ORDERS;
DELETE FROM CURVE_POINTS;
DELETE FROM CURVE_HEADERS;
DELETE FROM NEMO_HUBS;
DELETE FROM CCPS;
DELETE FROM NEMOS;
DELETE FROM SCHEDULING_AREAS;
DELETE FROM BIDDING_ZONES;
DELETE FROM BALANCING_AREAS;
DELETE FROM SESSIONS;


-- Sessions TABLE
INSERT INTO SESSIONS (SESSION_ID,NAME,DELIVERY_DATE,PERIODS,NETWORK_TYPE) VALUES (1, 'Circular_Test', '29-JAN-26', 9, 'HYBRID');

-- Balancing_Areas TABLE 
INSERT INTO Balancing_Areas(SESSION_ID,BALANCING_AREA_ID,NAME,EXTERNAL_ID,ADVERSE_FLOWS_ALLOWED,LTA_INCLUSION,TIME_RESOLUTION)VALUES(1,140,'Balancing Area - Greece Mainland','--PBAA--BA-GREE-',1,0,15);

-- Bidding_Zones TABLE
INSERT INTO Bidding_Zones(SESSION_ID,BIDDING_ZONE_ID,TIME_RESOLUTION,BALANCING_AREA_ID,SHORT_NAME,NAME,EXTERNAL_ID,MINIMUM_PRICE,MAXIMUM_PRICE,PRICE_PRECISION,NET_POSITION_PRECISION,CURVE_FORM,SHARE_CURTAILMENT_PMIN,SHARE_CURTAILMENT_PMAX,PERIOD_RAMPING,DAILY_RAMPING,PREVIOUS_DAY_LAST_NET_POSITION,ROUNDING_BIDDING_ZONE_ID,CLUSTER_ID,DECOUPLING) 
values (1,140,15,140,'GREE','Bidding Area - Greece Mainland','10YGR-HTSO-----Y',-500,4000,2,3,'HYBRID',1,1,0,0,null,null,null,0);

-- Scheduling_Areas TABLE
INSERT INTO Scheduling_Areas(SESSION_ID,SCHEDULING_AREA_ID,BIDDING_ZONE_ID,TIME_RESOLUTION,EXTERNAL_ID,NAME)VALUES(1,140,140,15,'10YGR-HTSO-----Y',null);

-- Nemos TABLE
INSERT INTO NEMOS(SESSION_ID,NEMO_ID,EXTERNAL_ID,NAME)VALUES(1,14,'29X100010001926U','HEnEx NEMO');

-- CCPS TABLE
INSERT INTO CCPS(SESSION_ID,CCP_ID,EXTERNAL_ID,NAME)VALUES(1,14,'29X100010001927S','HEnEx CCP');

-- Nemo_Hubs TABLE
INSERT INTO Nemo_Hubs(SESSION_ID,NEMO_HUB_ID,SCHEDULING_AREA_ID,TIME_RESOLUTION,EXTERNAL_ID,NEMO_ID,CCP_ID,NAME,CURVE_FORM)VALUES(1,1401,140,15,'10YGR-HTSO-----Y',14,14,'NEMO Hub - HENEX in GREE','HYBRID');


-- Lines TABLE
-- Linesets TABLE
-- Line_Period_Constraints TABLE
-- Lineset_Members TABLE
-- Lineset_Period_Constraints TABLE
-- Flow_Based_Headers TABLE
-- Flow_Based_Constraints TABLE
-- Flow_Based_Factors TABLE
-- Bidding_Zone_Daily_Constraints TABLE
-- Bidding_Zone_Period_Constraints TABLE
-- Scheduling_Area_Lines TABLE
-- Nemo_Hub_Lines TABLE

-- Curve_Headers TABLE
--for all time units (hours,30min,15min) included in the 9hour session

--DEMAND CURVE HEADERS
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,1,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,2,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,3,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,4,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,5,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,6,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,7,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,8,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,9,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,10,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,11,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,12,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,13,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,14,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,15,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,16,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,17,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,18,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,19,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,20,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,21,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,22,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,23,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,24,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,25,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,26,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,27,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,28,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,29,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,30,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,31,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,32,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,33,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,34,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,35,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,36,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,37,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,38,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,39,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,40,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,41,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,42,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,43,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,44,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,45,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,46,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,47,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,48,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,49,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,50,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,51,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,52,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,53,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,54,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,55,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,56,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,57,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,58,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,59,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,60,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,61,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,62,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,63,15,1401,4,'DEMAND');

-- SUPPLY CURVE_HEADERS
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,64,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,65,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,66,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,67,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,68,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,69,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,70,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,71,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,72,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,73,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,74,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,75,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,76,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,77,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,78,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,79,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,80,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,81,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,82,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,83,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,84,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,85,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,86,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,87,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,88,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,89,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,90,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,91,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,92,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,93,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,94,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,95,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,96,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,97,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,98,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,99,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,100,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,101,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,102,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,103,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,104,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,105,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,106,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,107,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,108,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,109,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,110,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,111,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,112,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,113,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,114,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,115,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,116,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,117,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,118,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,119,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,120,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,121,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,122,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,123,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,124,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,125,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,126,15,1401,4,'SUPPLY');



-- Curve_Points TABLE

--demand curve points 
--1ST POSITION IS MANDATORY TO BE (Q,P)=(0,4000)
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES
(1,1,1,0,4000),
(1,2,1,0,4000),
(1,3,1,0,4000),
(1,4,1,0,4000),
(1,5,1,0,4000),
(1,6,1,0,4000),
(1,7,1,0,4000),
(1,8,1,0,4000),
(1,9,1,0,4000),
(1,10,1,0,4000),
(1,11,1,0,4000),
(1,12,1,0,4000),
(1,13,1,0,4000),
(1,14,1,0,4000),
(1,15,1,0,4000),
(1,16,1,0,4000),
(1,17,1,0,4000),
(1,18,1,0,4000),
(1,19,1,0,4000),
(1,20,1,0,4000),
(1,21,1,0,4000),
(1,22,1,0,4000),
(1,23,1,0,4000),
(1,24,1,0,4000),
(1,25,1,0,4000),
(1,26,1,0,4000),
(1,27,1,0,4000),
(1,28,1,0,4000),
(1,29,1,0,4000),
(1,30,1,0,4000),
(1,31,1,0,4000),
(1,32,1,0,4000),
(1,33,1,0,4000),
(1,34,1,0,4000),
(1,35,1,0,4000),
(1,36,1,0,4000),
(1,37,1,0,4000),
(1,38,1,0,4000),
(1,39,1,0,4000),
(1,40,1,0,4000),
(1,41,1,0,4000),
(1,42,1,0,4000),
(1,43,1,0,4000),
(1,44,1,0,4000),
(1,45,1,0,4000),
(1,46,1,0,4000),
(1,47,1,0,4000),
(1,48,1,0,4000),
(1,49,1,0,4000),
(1,50,1,0,4000),
(1,51,1,0,4000),
(1,52,1,0,4000),
(1,53,1,0,4000),
(1,54,1,0,4000),
(1,55,1,0,4000),
(1,56,1,0,4000),
(1,57,1,0,4000),
(1,58,1,0,4000),
(1,59,1,0,4000),
(1,60,1,0,4000),
(1,61,1,0,4000),
(1,62,1,0,4000),
(1,63,1,0,4000);

--DEMAND HYBRID ORDERS
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,6,2,100,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,6,3,100,-500);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,7,2,100,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,7,3,100,-500);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,11,2,100,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,11,3,100,-500);

--supply curve points
--1ST POSITION IS MANDATORY TO BE (Q,P)=(0,-500)
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES
(1,64,1,0,-500),
(1,65,1,0,-500),
(1,66,1,0,-500),
(1,67,1,0,-500),
(1,68,1,0,-500),
(1,69,1,0,-500),
(1,70,1,0,-500),
(1,71,1,0,-500),
(1,72,1,0,-500),
(1,73,1,0,-500),
(1,74,1,0,-500),
(1,75,1,0,-500),
(1,76,1,0,-500),
(1,77,1,0,-500),
(1,78,1,0,-500),
(1,79,1,0,-500),
(1,80,1,0,-500),
(1,81,1,0,-500),
(1,82,1,0,-500),
(1,83,1,0,-500),
(1,84,1,0,-500),
(1,85,1,0,-500),
(1,86,1,0,-500),
(1,87,1,0,-500),
(1,88,1,0,-500),
(1,89,1,0,-500),
(1,90,1,0,-500),
(1,91,1,0,-500),
(1,92,1,0,-500),
(1,93,1,0,-500),
(1,94,1,0,-500),
(1,95,1,0,-500),
(1,96,1,0,-500),
(1,97,1,0,-500),
(1,98,1,0,-500),
(1,99,1,0,-500),
(1,100,1,0,-500),
(1,101,1,0,-500),
(1,102,1,0,-500),
(1,103,1,0,-500),
(1,104,1,0,-500),
(1,105,1,0,-500),
(1,106,1,0,-500),
(1,107,1,0,-500),
(1,108,1,0,-500),
(1,109,1,0,-500),
(1,110,1,0,-500),
(1,111,1,0,-500),
(1,112,1,0,-500),
(1,113,1,0,-500),
(1,114,1,0,-500),
(1,115,1,0,-500),
(1,116,1,0,-500),
(1,117,1,0,-500),
(1,118,1,0,-500),
(1,119,1,0,-500),
(1,120,1,0,-500),
(1,121,1,0,-500),
(1,122,1,0,-500),
(1,123,1,0,-500),
(1,124,1,0,-500),
(1,125,1,0,-500),
(1,126,1,0,-500);

--SUPPLY HYBRID ORDERS
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,76,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,76,3,100,4000);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,77,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,77,3,100,4000);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,81,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,81,3,100,4000);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,82,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,82,3,100,4000);


-- Merit_Orders TABLE
-- Complex_Orders TABLE 
-- Complex_Order_Points TABLE
-- Block_Order_Exclusive_Groups TABLE

-- Block_Orders TABLE

-- block 1 (Accepted with AR=0.5)
INSERT INTO BLOCK_ORDERS(SESSION_ID,BLOCK_ID,TIME_RESOLUTION,NEMO_HUB_ID,EXTERNAL_ID,TYPE,TIME_STAMP,SIDE,MIN_ACCEPTANCE_RATIO,PRICE,EXCLUSIVE_GROUP_ID,HASH)VALUES(1,1,15,1401,'10YGR-HTSO-----Y','C02',null,S,0.3,80,null,null);
INSERT INTO BLOCK_ORDERS(SESSION_ID,BLOCK_ID,TIME_RESOLUTION,NEMO_HUB_ID,EXTERNAL_ID,TYPE,TIME_STAMP,SIDE,MIN_ACCEPTANCE_RATIO,PRICE,EXCLUSIVE_GROUP_ID,HASH)VALUES(1,2,15,1401,'10YGR-HTSO-----Y','C02',null,B,0.5,100,null,null);

-- block 2 (REJECTED)
-- block 3 (CIRCULAR WITH SAME MTU SELL AND BUY OFFERS - ACCEPTED AR=100)

-- Block_Order_Links

-- block 1 (Accepted with AR=0.5)
INSERT INTO BLOCK_ORDER_LINKS(SESSION_ID,CHILD_BLOCK_ID,PARENT_BLOCK_ID)VALUES(1,2,1);
INSERT INTO BLOCK_ORDER_LINKS(SESSION_ID,CHILD_BLOCK_ID,PARENT_BLOCK_ID)VALUES(1,1,2);

-- block 2 (REJECTED)
-- block 3 (CIRCULAR WITH SAME MTU SELL AND BUY OFFERS - ACCEPTED AR=100)


-- Block_Order_Period_Constraints

-- block 1 (Accepted with AR=0.5)
INSERT INTO BLOCK_ORDERS_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,1,,);
INSERT INTO BLOCK_ORDERS_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,2,,);

-- block 2 (REJECTED)
-- block 3 (CIRCULAR WITH SAME MTU SELL AND BUY OFFERS - ACCEPTED AR=100)









-- Algorithm_Parameters
--Input checks
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'CHECK_TOPOLOGY_CURVES', 100000.0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'INPUT_CHECK_ATC', 0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'INPUT_CHECK_PTDF', 1 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'INPUT_CHECK_RAMPING_LINESET', 1 FROM SESSIONS);

--Network
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ENABLE_AAC', 0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'INTUITIVE', 0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PRIOR_CURTAILMENT_COEFF', 5.0E8 FROM SESSIONS);

--Complex orders
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'COMPLEX_MIC_DELTA', 0E0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'COMPLEX_MIC_PRICE_SHIFT', 7E-7 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'COMPLEX_TOXIC_TOL', 10.0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MPC_VT_TOPRICE', 180.3 FROM SESSIONS);

--Gap evaluation
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LOOK_GAP_WITH_DECOMPOSITION', 0 FROM SESSIONS);

--Tolerance levels
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ABS_IMBALANCE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ABS_IMBALANCE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ABS_IMB_DEF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ABS_IMB_DEF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ABS_NET_EXPOSURE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ABS_NET_EXPOSURE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ACCEPT_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ACCEPT_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ALLOW_PRC_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ALLOW_PRC_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ALPHA_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ALPHA_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ATC_CAP_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ATC_CAP_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ATC_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ATC_PRICE_TOL_TECH', 1E-4 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ATC_RAMPING_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ATC_RAMPING_TOL_TECH', 1E-4 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'BF_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'BF_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'BLOCK_ACTIVATE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'BLOCK_ACTIVATE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'BLOCK_EXCLUSIVE_GROUP_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'BLOCK_EXCLUSIVE_GROUP_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'BLOCK_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'BLOCK_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'B_ACCEPT_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'B_ACCEPT_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'CLEARING_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'CLEARING_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'COMPLEX_BLOCK_CUT_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'COMPLEX_BLOCK_CUT_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'COMPLEX_MICSUBHOURLY_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'COMPLEX_MICSUBHOURLY_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'COMPLEX_MIC_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'COMPLEX_MIC_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'COMPLEX_VOL_MIC_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'COMPLEX_VOL_MIC_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'CONSTRAINT_EXTERNAL_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'CONSTRAINT_EXTERNAL_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'CUMULATIVE_RAMPING_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'CUMULATIVE_RAMPING_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'CUM_RAMPING_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'CUM_RAMPING_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'DEVIATION_BALANCE_COMM_TOL_DECPL', 25.0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'DEVIATION_BALANCE_COMM_TOL_TECH', 25.0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'DEVIATION_BALANCE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'DEVIATION_BALANCE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'DEVIATION_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'DEVIATION_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FB_DEVIATION_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FB_DEVIATION_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FB_FLOW_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FB_FLOW_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FB_PRICE_DIFF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FB_PRICE_DIFF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FB_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FB_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FLOWS_BREAKDOWN_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FLOWS_BREAKDOWN_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FLOW_EQ_SHADOW_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FLOW_EQ_SHADOW_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FLOW_PLUS_AAC_DEF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FLOW_PLUS_AAC_DEF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FLOW_PLUS_AAC_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FLOW_PLUS_AAC_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FLOW_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'FLOW_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'GME_LINE_PRICE_DIFF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'GME_LINE_PRICE_DIFF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'INTUITIVE_CUT_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'INTUITIVE_CUT_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'INTUITIVE_PTDF_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'INTUITIVE_PTDF_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LG_PRICE_RELATION_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LG_PRICE_RELATION_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LG_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LG_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LG_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LG_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINESET_CAPACITY_LIMIT_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINESET_CAPACITY_LIMIT_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINESET_CAPACITY_LIMIT_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINESET_CAPACITY_LIMIT_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINESET_RAMPING_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINESET_RAMPING_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINESET_RAMPING_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINESET_RAMPING_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINE_PRICE_DIFF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINE_PRICE_DIFF_TOL_TECH', 1E-4 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINK_SURPLUS_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINK_SURPLUS_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINK_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LINK_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LOCAL_MATCHING_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LOCAL_MATCHING_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_DEVIATION_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_DEVIATION_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_FLOW_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_FLOW_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_PRICE_DIFF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_PRICE_DIFF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_SHADOW_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_SHADOW_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LTA_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_EXPORT_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_EXPORT_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_PRICE_LG_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_PRICE_LG_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_PRICE_NETWORK_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_PRICE_NETWORK_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_PRICE_ORDERS_BOUND_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_PRICE_ORDERS_BOUND_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_PRICE_ORDERS_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_PRICE_ORDERS_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_RAMPING_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_RAMPING_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_RAMPING_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MARKET_RAMPING_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MAX_CURTAILMENT_POWER_DEF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MAX_CURTAILMENT_POWER_DEF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MAX_CURTAILMENT_POWER_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MAX_CURTAILMENT_POWER_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MAX_CURTAILMENT_RATIO_DEF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MAX_CURTAILMENT_RATIO_DEF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MAX_CURTAILMENT_RATIO_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MAX_CURTAILMENT_RATIO_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MAX_SA_FLOW_DEF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MAX_SA_FLOW_DEF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MIN_ACC_POWER_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MIN_ACC_POWER_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MIN_ACC_RATIO_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MIN_ACC_RATIO_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MIN_VOL_H_PUN_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MIN_VOL_H_PUN_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NET_EXPORT_FB_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NET_EXPORT_FB_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NET_EXPORT_LTA_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NET_EXPORT_LTA_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NET_EXPOSURE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NET_EXPOSURE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NET_POSITION_BOUND_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NET_POSITION_BOUND_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NET_POSITION_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NET_POSITION_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NO_BF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NO_BF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NO_PAB_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'NO_PAB_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PRICE_COUPLING_FB_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PRICE_COUPLING_FB_TOL_TECH', 1E-4 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PRICE_COUPLING_LTA_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PRICE_COUPLING_LTA_TOL_TECH', 1E-4 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PRICE_RELATION_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PRICE_RELATION_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PTDF_COMM_TOL_DECPL', 25.0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PTDF_COMM_TOL_TECH', 25.0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PTDF_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PTDF_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PTDF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PTDF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PUN_IMBALANCE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PUN_IMBALANCE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PUN_IMBALANCE_VOL_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PUN_IMBALANCE_VOL_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PUN_IMB_DEF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PUN_IMB_DEF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PUN_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PUN_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PUN_VOL_IMB_DEF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PUN_VOL_IMB_DEF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'RAMPING_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'RAMPING_PRICE_TOL_TECH', 1E-4 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'RESERVE_NEEDED_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'RESERVE_NEEDED_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'RESERVE_PRICE_C_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'RESERVE_PRICE_C_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'RESERVE_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'RESERVE_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'RESERVE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'RESERVE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'SA_MAX_FLOW_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'SA_MAX_FLOW_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'SUBMODEL_COUPLING_SHADOW_PRICE_DOWN_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'SUBMODEL_COUPLING_SHADOW_PRICE_DOWN_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'SUBMODEL_COUPLING_SHADOW_PRICE_UP_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'SUBMODEL_COUPLING_SHADOW_PRICE_UP_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'SYSTEM_PRICE_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'SYSTEM_PRICE_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'TOTAL_DEVIATION_TOL_DECPL', 25.0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'TOTAL_DEVIATION_TOL_TECH', 25.0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'VOLUME_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'VOLUME_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'VOL_H_DEF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'VOL_H_DEF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'VOL_H_PUN_DEF_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'VOL_H_PUN_DEF_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'VOL_H_PUN_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'VOL_H_PUN_TOL_TECH', 1E-5 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'VOL_H_TOL_DECPL', 1E-3 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'VOL_H_TOL_TECH', 1E-5 FROM SESSIONS);

--Logging
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'BASES_ERASING', 0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'HEARTBEAT_INTERVAL', 20 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'HEARTBEAT_LOGGING', 1 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'LOG_WARNING_STATUS', 1 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'SOLVE_LOG', 1 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'VIOLATIONS_LOG', 2 FROM SESSIONS);

--Stopping criteria
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ADDITIONAL_TIME', 4800.0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'GRACE_TIME', 1200.0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'INTERRUPT_COMPUTATION', 0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'ITERATIONLIMIT', 999999999 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'SOLUTIONLIMIT', 999999999 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'TIMELIMIT', 1020.0 FROM SESSIONS);

--PUN orders
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MAX_PUN_IMB', 5.0 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MIN_PUN_IMB', -1E-2 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'MIN_PUN_POWER', 9.99999999E8 FROM SESSIONS);
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'PUN_POWER_PRECISION', 3 FROM SESSIONS);

--Block orders
INSERT INTO ALGORITHM_PARAMETERS (SELECT SESSION_ID, 'DELTA_P', 2.0 FROM SESSIONS);

