-- =======================================================================================================================================
-- Input file for Euphemia 11.4_fix3

--====: MEANS A TABLE SECTION
------: MEANS A CATEGORIZATION OF DATA INSIDE A TABLE
-- ====================================================================================================================================


-- =============================
-- delete TABLES DATA
DELETE FROM Block_Order_Period_Constraints;
DELETE FROM BLOCK_ORDER_LINKS;
DELETE FROM BLOCK_ORDERS;
DELETE FROM CURVE_POINTS;
DELETE FROM CURVE_HEADERS;
DELETE FROM NEMO_HUBS;
DELETE FROM CCPS;
DELETE FROM NEMOS;
DELETE FROM SCHEDULING_AREAS;
DELETE FROM BIDDING_ZONES;
DELETE FROM BALANCING_AREAS;
DELETE FROM SESSIONS;

-- =============================
-- Sessions TABLE
INSERT INTO SESSIONS (SESSION_ID,NAME,DELIVERY_DATE,PERIODS,NETWORK_TYPE) VALUES (1, 'Circular_Test', '29-JAN-26', 9, 'HYBRID');

-- =============================
-- Balancing_Areas TABLE 
INSERT INTO Balancing_Areas(SESSION_ID,BALANCING_AREA_ID,NAME,EXTERNAL_ID,ADVERSE_FLOWS_ALLOWED,LTA_INCLUSION,TIME_RESOLUTION)VALUES(1,140,'Balancing Area - Greece Mainland','--PBAA--BA-GREE-',1,0,15);

-- =============================
-- Bidding_Zones TABLE
INSERT INTO Bidding_Zones(SESSION_ID,BIDDING_ZONE_ID,TIME_RESOLUTION,BALANCING_AREA_ID,SHORT_NAME,NAME,EXTERNAL_ID,MINIMUM_PRICE,MAXIMUM_PRICE,PRICE_PRECISION,NET_POSITION_PRECISION,CURVE_FORM,SHARE_CURTAILMENT_PMIN,SHARE_CURTAILMENT_PMAX,PERIOD_RAMPING,DAILY_RAMPING,PREVIOUS_DAY_LAST_NET_POSITION,ROUNDING_BIDDING_ZONE_ID,CLUSTER_ID,DECOUPLING) 
values (1,140,15,140,'GREE','Bidding Area - Greece Mainland','10YGR-HTSO-----Y',-500,4000,2,3,'HYBRID',1,1,0,0,null,null,null,0);

-- =============================
-- Scheduling_Areas TABLE
INSERT INTO Scheduling_Areas(SESSION_ID,SCHEDULING_AREA_ID,BIDDING_ZONE_ID,TIME_RESOLUTION,EXTERNAL_ID,NAME)VALUES(1,140,140,15,'10YGR-HTSO-----Y',null);

-- =============================
-- Nemos TABLE
INSERT INTO NEMOS(SESSION_ID,NEMO_ID,EXTERNAL_ID,NAME)VALUES(1,14,'29X100010001926U','HEnEx NEMO');

-- =============================
-- CCPS TABLE
INSERT INTO CCPS(SESSION_ID,CCP_ID,EXTERNAL_ID,NAME)VALUES(1,14,'29X100010001927S','HEnEx CCP');

-- =============================
-- Nemo_Hubs TABLE
INSERT INTO Nemo_Hubs(SESSION_ID,NEMO_HUB_ID,SCHEDULING_AREA_ID,TIME_RESOLUTION,EXTERNAL_ID,NEMO_ID,CCP_ID,NAME,CURVE_FORM)VALUES(1,1401,140,15,'10YGR-HTSO-----Y',14,14,'NEMO Hub - HENEX in GREE','HYBRID');

-- =============================
-- Lines TABLE

-- =============================
-- Linesets TABLE

-- =============================
-- Line_Period_Constraints TABLE

-- =============================
-- Lineset_Members TABLE

-- =============================
-- Lineset_Period_Constraints TABLE

-- =============================
-- Flow_Based_Headers TABLE

-- =============================
-- Flow_Based_Constraints TABLE

-- =============================
-- Flow_Based_Factors TABLE

-- =============================
-- Bidding_Zone_Daily_Constraints TABLE

-- =============================
-- Bidding_Zone_Period_Constraints TABLE

-- =============================
-- Scheduling_Area_Lines TABLE

-- =============================
-- Nemo_Hub_Lines TABLE

-- ===============================================================================================================================================
-- Curve_Headers TABLE
-- 1. it must be defined for each Nemo_hub_id
-- 2. it must be defined for both demand and supply 
-- 3. it must be defined for all time units (hours,30min,15min) included in the session's hours

-- 1. Henex Hub ----------------------------------------------------------------------------

-- 2. DEMAND CURVE HEADERS ------------------------------
-- 3. 60 λεπτά PERIOD 1..9 (CURVE_ID 1..9)
INSERT INTO Curve_Headers VALUES (1,1,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,2,60,1401,2,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,3,60,1401,3,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,4,60,1401,4,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,5,60,1401,5,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,6,60,1401,6,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,7,60,1401,7,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,8,60,1401,8,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,9,60,1401,9,'DEMAND');

-- 3. 30 λεπτά PERIOD 1..18 (CURVE_ID 10..27)
INSERT INTO Curve_Headers VALUES (1,10,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,11,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,12,30,1401,3,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,13,30,1401,4,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,14,30,1401,5,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,15,30,1401,6,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,16,30,1401,7,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,17,30,1401,8,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,18,30,1401,9,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,19,30,1401,10,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,20,30,1401,11,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,21,30,1401,12,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,22,30,1401,13,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,23,30,1401,14,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,24,30,1401,15,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,25,30,1401,16,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,26,30,1401,17,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,27,30,1401,18,'DEMAND');

--3. 15 λεπτά PERIOD 1..36 (CURVE_ID 28..63)
INSERT INTO Curve_Headers VALUES (1,28,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,29,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,30,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,31,15,1401,4,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,32,15,1401,5,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,33,15,1401,6,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,34,15,1401,7,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,35,15,1401,8,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,36,15,1401,9,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,37,15,1401,10,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,38,15,1401,11,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,39,15,1401,12,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,40,15,1401,13,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,41,15,1401,14,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,42,15,1401,15,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,43,15,1401,16,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,44,15,1401,17,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,45,15,1401,18,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,46,15,1401,19,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,47,15,1401,20,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,48,15,1401,21,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,49,15,1401,22,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,50,15,1401,23,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,51,15,1401,24,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,52,15,1401,25,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,53,15,1401,26,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,54,15,1401,27,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,55,15,1401,28,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,56,15,1401,29,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,57,15,1401,30,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,58,15,1401,31,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,59,15,1401,32,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,60,15,1401,33,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,61,15,1401,34,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,62,15,1401,35,'DEMAND');
INSERT INTO Curve_Headers VALUES (1,63,15,1401,36,'DEMAND');


--2. SUPPLY CURVE_HEADERS --------------------------------------------------

--3. 60 λεπτά PERIOD 1..9 (CURVE_ID 64..72)
INSERT INTO Curve_Headers VALUES (1,64,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,65,60,1401,2,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,66,60,1401,3,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,67,60,1401,4,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,68,60,1401,5,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,69,60,1401,6,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,70,60,1401,7,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,71,60,1401,8,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,72,60,1401,9,'SUPPLY');

--3. 30 λεπτά PERIOD 1..18 (CURVE_ID 73..90)
INSERT INTO Curve_Headers VALUES (1,73,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,74,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,75,30,1401,3,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,76,30,1401,4,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,77,30,1401,5,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,78,30,1401,6,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,79,30,1401,7,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,80,30,1401,8,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,81,30,1401,9,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,82,30,1401,10,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,83,30,1401,11,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,84,30,1401,12,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,85,30,1401,13,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,86,30,1401,14,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,87,30,1401,15,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,88,30,1401,16,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,89,30,1401,17,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,90,30,1401,18,'SUPPLY');

--3. 15 λεπτά PERIOD 1..36 (CURVE_ID 91..126)
INSERT INTO Curve_Headers VALUES (1,91,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,92,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,93,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,94,15,1401,4,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,95,15,1401,5,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,96,15,1401,6,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,97,15,1401,7,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,98,15,1401,8,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,99,15,1401,9,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,100,15,1401,10,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,101,15,1401,11,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,102,15,1401,12,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,103,15,1401,13,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,104,15,1401,14,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,105,15,1401,15,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,106,15,1401,16,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,107,15,1401,17,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,108,15,1401,18,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,109,15,1401,19,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,110,15,1401,20,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,111,15,1401,21,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,112,15,1401,22,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,113,15,1401,23,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,114,15,1401,24,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,115,15,1401,25,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,116,15,1401,26,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,117,15,1401,27,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,118,15,1401,28,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,119,15,1401,29,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,120,15,1401,30,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,121,15,1401,31,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,122,15,1401,32,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,123,15,1401,33,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,124,15,1401,34,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,125,15,1401,35,'SUPPLY');
INSERT INTO Curve_Headers VALUES (1,126,15,1401,36,'SUPPLY');


-- ======================================================================================================================================
-- Curve_Points TABLE
-- it must be defined for all curve_id 
-- Curve_id categorised in 1. DEMAND and 2. SUPPLY for convinience

-- 1. DEMAND CURVE_POINTS ----------------------------------------------------------------------------------
--1ST POSITION IS MANDATORY TO BE (Q,P)=(0,4000)
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,1,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,2,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,3,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,4,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,5,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,6,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,7,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,8,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,9,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,10,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,11,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,12,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,13,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,14,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,15,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,16,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,17,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,18,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,19,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,20,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,21,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,22,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,23,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,24,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,25,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,26,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,27,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,28,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,29,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,30,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,31,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,32,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,33,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,34,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,35,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,36,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,37,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,38,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,39,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,40,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,41,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,42,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,43,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,44,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,45,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,46,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,47,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,48,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,49,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,50,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,51,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,52,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,53,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,54,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,55,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,56,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,57,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,58,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,59,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,60,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,61,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,62,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,63,1,0,4000);


-- 1. DEMAND HYBRID ORDERS-------------------------------------------------------------------
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,30,2,100,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,30,3,100,-500);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,31,2,100,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,31,3,100,-500);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,32,2,100,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,32,3,100,-500);

-- 2. SUPPLY CURVE POINTS ------------------------------------------------------------------------------------
--1ST POSITION IS MANDATORY TO BE (Q,P)=(0,-500)
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,64,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,65,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,66,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,67,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,68,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,69,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,70,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,71,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,72,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,73,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,74,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,75,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,76,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,77,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,78,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,79,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,80,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,81,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,82,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,83,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,84,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,85,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,86,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,87,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,88,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,89,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,90,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,91,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,92,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,93,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,94,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,95,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,96,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,97,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,98,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,99,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,100,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,101,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,102,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,103,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,104,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,105,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,106,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,107,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,108,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,109,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,110,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,111,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,112,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,113,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,114,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,115,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,116,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,117,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,118,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,119,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,120,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,121,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,122,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,123,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,124,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,125,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,126,1,0,-500);


-- 2. SUPPLY HYBRID ORDERS-----------------------------------------------------------------------
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,97,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,97,3,100,4000);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,98,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,98,3,100,4000);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,99,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,99,3,100,4000);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,100,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,100,3,100,400);

-- =====================================================================
-- Merit_Orders TABLE

-- =====================================================================
-- Complex_Orders TABLE 

-- =====================================================================
-- Complex_Order_Points TABLE

-- =====================================================================
-- Block_Order_Exclusive_Groups TABLE

-- =======================================================================================================================================================
-- Block_Orders TABLE 
-- Noticed: Need different External ID to work

-- block 1 (Accepted with AR=0.5)--------------------------------------------------------------------------------------------
INSERT INTO BLOCK_ORDERS(SESSION_ID,BLOCK_ID,TIME_RESOLUTION,NEMO_HUB_ID,EXTERNAL_ID,TYPE,TIME_STAMP,SIDE,MIN_ACCEPTANCE_RATIO,PRICE,EXCLUSIVE_GROUP_ID,HASH)VALUES(1,1,15,1401,'ID1','C02',TO_TIMESTAMP('2026-01-29 00:45:00', 'YYYY-MM-DD HH24:MI:SS'),'S',0.3,80,null,null);
INSERT INTO BLOCK_ORDERS(SESSION_ID,BLOCK_ID,TIME_RESOLUTION,NEMO_HUB_ID,EXTERNAL_ID,TYPE,TIME_STAMP,SIDE,MIN_ACCEPTANCE_RATIO,PRICE,EXCLUSIVE_GROUP_ID,HASH)VALUES(1,2,15,1401,'ID2','C02',TO_TIMESTAMP('2026-01-29 00:45:00', 'YYYY-MM-DD HH24:MI:SS'),'B',0.5,100,null,null);

-- block 2 (REJECTED)--------------------------------------------------------------------------------------------------------
INSERT INTO BLOCK_ORDERS(SESSION_ID,BLOCK_ID,TIME_RESOLUTION,NEMO_HUB_ID,EXTERNAL_ID,TYPE,TIME_STAMP,SIDE,MIN_ACCEPTANCE_RATIO,PRICE,EXCLUSIVE_GROUP_ID,HASH)VALUES(1,3,15,1401,'ID3','C02',TO_TIMESTAMP('2026-01-29 00:45:00', 'YYYY-MM-DD HH24:MI:SS'),'S',1,80,null,null);
INSERT INTO BLOCK_ORDERS(SESSION_ID,BLOCK_ID,TIME_RESOLUTION,NEMO_HUB_ID,EXTERNAL_ID,TYPE,TIME_STAMP,SIDE,MIN_ACCEPTANCE_RATIO,PRICE,EXCLUSIVE_GROUP_ID,HASH)VALUES(1,4,15,1401,'ID4','C02',TO_TIMESTAMP('2026-01-29 00:45:00', 'YYYY-MM-DD HH24:MI:SS'),'B',1,100,null,null);


-- block 3 (CIRCULAR WITH SAME MTU SELL AND BUY OFFERS - ACCEPTED AR=100)----------------------------------------------------
INSERT INTO BLOCK_ORDERS(SESSION_ID,BLOCK_ID,TIME_RESOLUTION,NEMO_HUB_ID,EXTERNAL_ID,TYPE,TIME_STAMP,SIDE,MIN_ACCEPTANCE_RATIO,PRICE,EXCLUSIVE_GROUP_ID,HASH)VALUES(1,5,15,1401,'ID5','C02',TO_TIMESTAMP('2026-01-29 00:45:00', 'YYYY-MM-DD HH24:MI:SS'),'S',1,80,null,null);
INSERT INTO BLOCK_ORDERS(SESSION_ID,BLOCK_ID,TIME_RESOLUTION,NEMO_HUB_ID,EXTERNAL_ID,TYPE,TIME_STAMP,SIDE,MIN_ACCEPTANCE_RATIO,PRICE,EXCLUSIVE_GROUP_ID,HASH)VALUES(1,6,15,1401,'ID6','C02',TO_TIMESTAMP('2026-01-29 00:45:00', 'YYYY-MM-DD HH24:MI:SS'),'B',1,100,null,null);


-- =========================================================================================================================================================
-- Block_Order_Links TABLE

-- block 1 (Accepted with AR=0.5)--------------------------------------------------------------------------------------------
INSERT INTO BLOCK_ORDER_LINKS(SESSION_ID,CHILD_BLOCK_ID,PARENT_BLOCK_ID)VALUES(1,1,2);
INSERT INTO BLOCK_ORDER_LINKS(SESSION_ID,CHILD_BLOCK_ID,PARENT_BLOCK_ID)VALUES(1,2,1);

-- block 2 (REJECTED)--------------------------------------------------------------------------------------------------------
INSERT INTO BLOCK_ORDER_LINKS(SESSION_ID,CHILD_BLOCK_ID,PARENT_BLOCK_ID)VALUES(1,3,4);
INSERT INTO BLOCK_ORDER_LINKS(SESSION_ID,CHILD_BLOCK_ID,PARENT_BLOCK_ID)VALUES(1,4,3);

-- block 3 (CIRCULAR WITH SAME MTU SELL AND BUY OFFERS - ACCEPTED AR=100)----------------------------------------------------
INSERT INTO BLOCK_ORDER_LINKS(SESSION_ID,CHILD_BLOCK_ID,PARENT_BLOCK_ID)VALUES(1,5,6);
INSERT INTO BLOCK_ORDER_LINKS(SESSION_ID,CHILD_BLOCK_ID,PARENT_BLOCK_ID)VALUES(1,6,5);

-- ==========================================================================================================================================================
-- Block_Order_Period_Constraints TABLE

--Circular linked block 1 (Accepted with AR=0.5)--------------------------------------------------------------------------------------------
--Sell block
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,1,3,130);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,1,4,140);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,1,5,150);

--Buy Block
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,2,7,170);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,2,8,180);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,2,9,190);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,2,10,200);


-- Circular linked block 2 (REJECTED)--------------------------------------------------------------------------------------------------------
--Sell block
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,3,23,203);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,3,24,204);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,3,25,205);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,3,26,206);

--Buy block
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,4,28,208);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,4,29,209);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,4,30,300);


--Circular linked block 3 (CIRCULAR WITH SAME MTU SELL AND BUY OFFERS - ACCEPTED AR=100)----------------------------------------------------
--Sell block
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,5,32,302);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,5,33,303);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,5,34,304);


--Buy Block
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,6,32,302);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,6,33,303);
INSERT INTO BLOCK_ORDER_PERIOD_CONSTRAINTS(SESSION_ID,BLOCK_ID,PERIOD,POWER)VALUES(1,6,34,304);