-- Input file for Euphemia 11.4_fix3

-- delete TABLES DATA
DELETE FROM Algorithm_Parameters;
DELETE FROM Block_Order_Period_Constraints;
DELETE FROM BLOCK_ORDER_LINKS;
DELETE FROM BLOCK_ORDERS;
DELETE FROM CURVE_POINTS;
DELETE FROM CURVE_HEADERS;
DELETE FROM NEMO_HUBS;
DELETE FROM CCPS;
DELETE FROM NEMOS;
DELETE FROM SCHEDULING_AREAS;
DELETE FROM BIDDING_ZONES;
DELETE FROM BALANCING_AREAS;
DELETE FROM SESSIONS;


-- Sessions TABLE
INSERT INTO SESSIONS (SESSION_ID,NAME,DELIVERY_DATE,PERIODS,NETWORK_TYPE) VALUES (1, 'Circular_Test', '29-JAN-26', 9, 'HYBRID');

-- Balancing_Areas TABLE 
INSERT INTO Balancing_Areas(SESSION_ID,BALANCING_AREA_ID,NAME,EXTERNAL_ID,ADVERSE_FLOWS_ALLOWED,LTA_INCLUSION,TIME_RESOLUTION)VALUES(1,140,'Balancing Area - Greece Mainland','--PBAA--BA-GREE-',1,0,15);

-- Bidding_Zones TABLE
INSERT INTO Bidding_Zones(SESSION_ID,BIDDING_ZONE_ID,TIME_RESOLUTION,BALANCING_AREA_ID,SHORT_NAME,NAME,EXTERNAL_ID,MINIMUM_PRICE,MAXIMUM_PRICE,PRICE_PRECISION,NET_POSITION_PRECISION,CURVE_FORM,SHARE_CURTAILMENT_PMIN,SHARE_CURTAILMENT_PMAX,PERIOD_RAMPING,DAILY_RAMPING,PREVIOUS_DAY_LAST_NET_POSITION,ROUNDING_BIDDING_ZONE_ID,CLUSTER_ID,DECOUPLING) 
values (1,140,15,140,'GREE','Bidding Area - Greece Mainland','10YGR-HTSO-----Y',-500,4000,2,3,'HYBRID',1,1,0,0,null,null,null,0);

-- Scheduling_Areas TABLE
INSERT INTO Scheduling_Areas(SESSION_ID,SCHEDULING_AREA_ID,BIDDING_ZONE_ID,TIME_RESOLUTION,EXTERNAL_ID,NAME)VALUES(1,140,140,15,'10YGR-HTSO-----Y',null);

-- Nemos TABLE
INSERT INTO NEMOS(SESSION_ID,NEMO_ID,EXTERNAL_ID,NAME)VALUES(1,14,'29X100010001926U','HEnEx NEMO');

-- CCPS TABLE
INSERT INTO CCPS(SESSION_ID,CCP_ID,EXTERNAL_ID,NAME)VALUES(1,14,'29X100010001927S','HEnEx CCP');

-- Nemo_Hubs TABLE
INSERT INTO Nemo_Hubs(SESSION_ID,NEMO_HUB_ID,SCHEDULING_AREA_ID,TIME_RESOLUTION,EXTERNAL_ID,NEMO_ID,CCP_ID,NAME,CURVE_FORM)VALUES(1,1401,140,15,'10YGR-HTSO-----Y',14,14,'NEMO Hub - HENEX in GREE','HYBRID');


-- Lines TABLE
-- Linesets TABLE
-- Line_Period_Constraints TABLE
-- Lineset_Members TABLE
-- Lineset_Period_Constraints TABLE
-- Flow_Based_Headers TABLE
-- Flow_Based_Constraints TABLE
-- Flow_Based_Factors TABLE
-- Bidding_Zone_Daily_Constraints TABLE
-- Bidding_Zone_Period_Constraints TABLE
-- Scheduling_Area_Lines TABLE
-- Nemo_Hub_Lines TABLE

-- Curve_Headers TABLE
--for all time units (hours,30min,15min) included in the 9hour session

--DEMAND CURVE HEADERS
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,1,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,2,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,3,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,4,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,5,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,6,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,7,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,8,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,9,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,10,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,11,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,12,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,13,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,14,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,15,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,16,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,17,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,18,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,19,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,20,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,21,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,22,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,23,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,24,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,25,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,26,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,27,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,28,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,29,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,30,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,31,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,32,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,33,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,34,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,35,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,36,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,37,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,38,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,39,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,40,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,41,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,42,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,43,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,44,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,45,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,46,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,47,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,48,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,49,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,50,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,51,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,52,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,53,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,54,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,55,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,56,15,1401,4,'DEMAND');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,57,60,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,58,30,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,59,30,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,60,15,1401,1,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,61,15,1401,2,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,62,15,1401,3,'DEMAND');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,63,15,1401,4,'DEMAND');

-- SUPPLY CURVE_HEADERS
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,64,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,65,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,66,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,67,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,68,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,69,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,70,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,71,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,72,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,73,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,74,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,75,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,76,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,77,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,78,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,79,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,80,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,81,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,82,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,83,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,84,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,85,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,86,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,87,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,88,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,89,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,90,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,91,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,92,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,93,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,94,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,95,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,96,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,97,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,98,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,99,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,100,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,101,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,102,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,103,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,104,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,105,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,106,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,107,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,108,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,109,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,110,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,111,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,112,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,113,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,114,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,115,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,116,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,117,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,118,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,119,15,1401,4,'SUPPLY');

INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,120,60,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,121,30,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,122,30,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,123,15,1401,1,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,124,15,1401,2,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,125,15,1401,3,'SUPPLY');
INSERT INTO Curve_Headers(SESSION_ID,CURVE_ID,TIME_RESOLUTION,NEMO_HUB_ID,PERIOD,SIDE) VALUES (1,126,15,1401,4,'SUPPLY');



-- Curve_Points TABLE

--demand curve points 
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,1,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,2,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,3,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,4,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,5,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,6,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,7,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,8,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,9,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,10,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,11,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,12,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,13,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,14,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,15,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,16,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,17,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,18,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,19,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,20,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,21,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,22,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,23,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,24,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,25,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,26,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,27,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,28,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,29,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,30,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,31,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,32,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,33,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,34,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,35,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,36,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,37,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,38,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,39,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,40,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,41,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,42,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,43,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,44,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,45,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,46,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,47,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,48,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,49,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,50,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,51,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,52,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,53,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,54,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,55,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,56,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,57,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,58,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,59,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,60,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,61,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,62,1,0,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,63,1,0,4000);

--DEMAND HYBRID ORDERS
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,6,2,100,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,6,3,100,-500);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,7,2,100,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,7,3,100,-500);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,11,2,100,4000);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,11,3,100,-500);

--supply curve points
--1ST POSITION IS MANDATORY TO BE (Q,P)=(0,-500)
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,64,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,65,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,66,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,67,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,68,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,69,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,70,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,71,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,72,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,73,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,74,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,75,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,76,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,77,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,78,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,79,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,80,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,81,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,82,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,83,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,84,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,85,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,86,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,87,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,88,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,89,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,90,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,91,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,92,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,93,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,94,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,95,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,96,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,97,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,98,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,99,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,100,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,101,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,102,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,103,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,104,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,105,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,106,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,107,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,108,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,109,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,110,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,111,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,112,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,113,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,114,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,115,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,116,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,117,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,118,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,119,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,120,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,121,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,122,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,123,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,124,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,125,1,0,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE) VALUES (1,126,1,0,-500);


--SUPPLY HYBRID ORDERS
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,76,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,76,3,100,4000);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,77,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,77,3,100,4000);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,81,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,81,3,100,4000);

INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,82,2,100,-500);
INSERT INTO Curve_Points(SESSION_ID,CURVE_ID,POSITION,POWER,PRICE)VALUES(1,82,3,100,4000);


-- Merit_Orders TABLE
-- Complex_Orders TABLE 
-- Complex_Order_Points TABLE
-- Block_Order_Exclusive_Groups TABLE
-- Block_Orders TABLE
-- Block_Order_Links TABLE
-- Block_Order_Period_Constraints TABLE
