WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE

SET VERIFY OFF;
SET ECHO OFF
SET HEADING OFF
SET FEEDBACK OFF
SET UNDERLINE OFF
SET TIMING OFF
SET PAGESIZE 0

DEFINE USER_NAME=Circular;
DEFINE USER_PSWD="Circular";
DEFINE TABLE_SPACE=EUPHEMIA_DATA;
DEFINE FOLDER_DMP=DATA_PUMP_PCR;

CREATE USER &USER_NAME IDENTIFIED BY &USER_PSWD DEFAULT TABLESPACE &TABLE_SPACE;
GRANT connect, resource TO &USER_NAME;
GRANT create table, create view, create procedure, create sequence TO &USER_NAME;
GRANT read, write ON DIRECTORY &FOLDER_DMP TO &USER_NAME;
GRANT UNLIMITED TABLESPACE TO  &USER_NAME;

exit;
